apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app
  namespace: app
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: app-vault-backend
  namespace: app
spec:
  provider:
    vault:
      server: "https://vault.mydomain.com"
      path: "app"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "k8s"
          role: "role_app"
          serviceAccountRef:
            name: "sa-app"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: app
spec:
  refreshInterval: "20s"
  secretStoreRef:
    name: app-vault-backend
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
  annotations:
    secret.reloader.stakater.com/reload: app-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: sa-app
      containers:
        - name: vault-demo-app
          image: brunopadz/vault-demo-app:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "16Mi"
              cpu: "100m"
            limits:
              memory: "16Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  namespace: app
spec:
  selector:
    app: app
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  namespace: app
spec:
  ingressClassName: nginx
  rules:
    - host: hello.mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-app
                port:
                  number: 3000
